### ISSUE TITLE
CHYT queries hang in the web-UI

### ISSUE THREAD

**Issue by oartemev** [ytsaurus/ytsaurus#105]
Any CHYT queries launched in the web-UI are infinitely in the 'pending' state, even if they are aborted and the clique is stopped.
In the CLI CHYT works well.

The used images:
```
  coreImage: ytsaurus/ytsaurus:stable-23.1.0-relwithdebinfo
  uiImage: ytsaurus/ui:stable

  strawberry:
    image: ytsaurus/strawberry:0.0.5

  queryTrackers:
    image: ytsaurus/query-tracker-nightly:dev-66905-ecb23a91d6e5b9e427b74bc9b4bb1698853ad8de-relwithdebinfo

  yqlAgents:
    image: ytsaurus/query-tracker-nightly:dev-66905-ecb23a91d6e5b9e427b74bc9b4bb1698853ad8de-relwithdebinfo
```

The query-tracker logs are attached.
[query-tracker.info.log](https://github.com/ytsaurus/ytsaurus/files/12789131/query-tracker.info.log)
[query-tracker.debug.log](https://github.com/ytsaurus/ytsaurus/files/12789132/query-tracker.debug.log)
