### ISSUE TITLE
can't run yt by minikube

### ISSUE THREAD

**Issue by dawsongzhao** [ytsaurus/ytsaurus#59]
can't run yt by minikube following the instuctions of https://ytsaurus.tech/docs/en/overview/try-yt#kubernetes
<img width="1725" alt="image" src="https://github.com/ytsaurus/ytsaurus/assets/7078308/02d5b938-32b8-430c-bbc5-8c73d3a29a5c">

**Comment by savnadya** [comment]
Hello!
Probably this version of `ytop-chart` doesn't support different proxies groups. Try to change `httpProxies` and `rpcProxies` fields in `cluster_v1_minikube.yaml`:
```
  httpProxies:
    - serviceType: NodePort
      instanceCount: 1
  rpcProxies:
    - instanceCount: 1
```
